ladders:
	perl ladders.pl

laddersprof:
	perl -d:NYTProf ladders.pl && nytprofhtml

ladders-g:
	perl -d:NYTProf ladders-g.pl && nytprofhtml

ladders-gprof:
	perl -d:NYTProf ladders-g.pl && nytprofhtml
